[package]
name = "yql-server"
version = "0.1.0"
authors = ["Sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.6.0", features = ["rt-multi-thread", "macros"] }

[workspace]
members = [
    "libs/core",
    "libs/service",
]