[package]
name = "yql-cli"
version = "0.1.0"
authors = ["Sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11.3", default-features = false, features = ["rustls-tls", "gzip", "json", "brotli"] }
rustyline = "8.2.0"
structopt = "0.3.21"
